### ISSUE TITLE
where is the bitcointalk link? Also the discord one as I cannot see them

### ISSUE THREAD

**Issue by NotYourTypicalPerson** [xcn-project/cryonote-old#1]
where is the bitcointalk link? Also the discord one as I cannot see them.

**Comment by osamadeep** [comment]
https://bitcointalk.org/index.php?topic=2973679.0

**Comment by NotYourTypicalPerson** [comment]
Is this the official admin posting?

**Comment by xcn-project** [comment]
That is the official BitcoinTalk ANN page.
